//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSSPDBDLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PolSourceGroupingLanguage
    {
        public int PolSourceGroupingLanguageID { get; set; }
        public int DBCommand { get; set; }
        public int PolSourceGroupingID { get; set; }
        public int Language { get; set; }
        public string SourceName { get; set; }
        public int SourceNameOrder { get; set; }
        public int TranslationStatusSourceName { get; set; }
        public string Init { get; set; }
        public int TranslationStatusInit { get; set; }
        public string Description { get; set; }
        public int TranslationStatusDescription { get; set; }
        public string Report { get; set; }
        public int TranslationStatusReport { get; set; }
        public string Text { get; set; }
        public int TranslationStatusText { get; set; }
        public System.DateTime LastUpdateDate_UTC { get; set; }
        public int LastUpdateContactTVItemID { get; set; }
    
        public virtual PolSourceGrouping PolSourceGrouping { get; set; }
    }
}
