//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSSPDBDLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PolSourceGrouping
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PolSourceGrouping()
        {
            this.PolSourceGroupingLanguages = new HashSet<PolSourceGroupingLanguage>();
        }
    
        public int PolSourceGroupingID { get; set; }
        public int CSSPID { get; set; }
        public string GroupName { get; set; }
        public string Child { get; set; }
        public string Hide { get; set; }
        public System.DateTime LastUpdateDate_UTC { get; set; }
        public int LastUpdateContactTVItemID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PolSourceGroupingLanguage> PolSourceGroupingLanguages { get; set; }
    }
}
