//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSSPDBDLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RainExceedance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RainExceedance()
        {
            this.RainExceedanceClimateSites = new HashSet<RainExceedanceClimateSite>();
        }
    
        public int RainExceedanceID { get; set; }
        public int RainExceedanceTVItemID { get; set; }
        public int StartMonth { get; set; }
        public int StartDay { get; set; }
        public int EndMonth { get; set; }
        public int EndDay { get; set; }
        public double RainMaximum_mm { get; set; }
        public Nullable<int> StakeholdersEmailDistributionListID { get; set; }
        public Nullable<int> OnlyStaffEmailDistributionListID { get; set; }
        public System.DateTime LastUpdateDate_UTC { get; set; }
        public int LastUpdateContactTVItemID { get; set; }
    
        public virtual EmailDistributionList EmailDistributionList { get; set; }
        public virtual EmailDistributionList EmailDistributionList1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RainExceedanceClimateSite> RainExceedanceClimateSites { get; set; }
        public virtual TVItem TVItem { get; set; }
    }
}
