//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSSPDBDLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RainExceedanceClimateSite
    {
        public int RainExceedanceClimateSiteID { get; set; }
        public int RainExceedanceID { get; set; }
        public int ClimateSiteID { get; set; }
        public System.DateTime LastUpdateDate_UTC { get; set; }
        public int LastUpdateContactTVItemID { get; set; }
    
        public virtual ClimateSite ClimateSite { get; set; }
        public virtual RainExceedance RainExceedance { get; set; }
    }
}
